/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export type Uint128 = string;
export type Addr = string;
export interface InstantiateMsg {
  collection_params: CollectionParams;
  init_msg: Empty;
  manager_params: CharacterManagerParams;
}
export interface CollectionParams {
  code_id: number;
  info: CollectionInfoForRoyaltyInfoResponse;
  name: string;
  symbol?: string | null;
}
export interface CollectionInfoForRoyaltyInfoResponse {
  creator: string;
  description: string;
  explicit_content?: boolean | null;
  external_link?: string | null;
  image?: string | null;
  royalty_info?: RoyaltyInfoResponse | null;
}
export interface RoyaltyInfoResponse {
  payment_address: string;
  share: Decimal;
}
export interface Empty {
  [k: string]: unknown;
}
export interface CharacterManagerParams {
  burn_ratio: number;
  character_mint_prices: Coin[];
  character_rarities: string[];
  destination?: Addr | null;
  empty_character_mint_price: Coin;
  mintable_collection_addr: Addr;
  trait_collection_addr: Addr;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  mint: {
    token_info: Metadata;
  };
} | {
  mint_to: {
    receiver: string;
    token_info: Metadata;
  };
} | {
  mint_bundle: {
    bundle_id: number;
    receiver?: string | null;
  };
} | {
  open_lootbox: {
    lootbox_id: number;
    receiver?: string | null;
  };
} | {
  change_name: {
    new_name: string;
    token_id: string;
  };
} | {
  modify_character: {
    token_id: string;
    trait_ids: string[];
  };
} | {
  lock_character: {
    token_id: string;
  };
} | {
  update_config: {
    new_config: UpdateCharacterManagerParamsMsg;
  };
} | {
  update_ownership: Action;
};
export type Action = {
  transfer_ownership: {
    expiry?: Expiration | null;
    new_owner: string;
  };
} | "accept_ownership" | "renounce_ownership";
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface Metadata {
  ears?: string | null;
  eyes?: string | null;
  fur_color?: string | null;
  fur_type?: string | null;
  locked: boolean;
  mouth?: string | null;
  name?: string | null;
  rarity?: string | null;
  tail_shape?: string | null;
  traits_equipped?: string[] | null;
}
export interface UpdateCharacterManagerParamsMsg {
  burn_ratio: number;
  character_mint_prices: Coin[];
  character_rarities: string[];
  destination?: Addr | null;
  empty_character_mint_price: Coin;
}
export type QueryMsg = {
  config: {};
} | {
  allowed_collection_code_id: {};
};
export interface AllowedCollectionCodeIdResponse {
  code_id: number;
}
export interface CharacterManagerConfigResponseForEmpty {
  collection_address: string;
  config: CharacterManagerConfigForEmpty;
}
export interface CharacterManagerConfigForEmpty {
  burn_ratio: number;
  collection_code_id: number;
  destination?: Addr | null;
  empty_character_mint_price: Coin;
  extension: Empty;
}
export type CCATCharacterManagerExecuteMsg = ExecuteMsg;