/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CWAdminFactory.types";
import * as _1 from "./CWAdminFactory.client";
import * as _2 from "./CWAdminFactory.message-composer";
import * as _3 from "./CWCore.types";
import * as _4 from "./CWCore.client";
import * as _5 from "./CWCore.message-composer";
import * as _6 from "./CWNamedGroups.types";
import * as _7 from "./CWNamedGroups.client";
import * as _8 from "./CWNamedGroups.message-composer";
import * as _9 from "./CWNamesRegistry.types";
import * as _10 from "./CWNamesRegistry.client";
import * as _11 from "./CWNamesRegistry.message-composer";
import * as _12 from "./CWNativeStakedBalanceVoting.types";
import * as _13 from "./CWNativeStakedBalanceVoting.client";
import * as _14 from "./CWNativeStakedBalanceVoting.message-composer";
import * as _15 from "./CWProposalMultiple.types";
import * as _16 from "./CWProposalMultiple.client";
import * as _17 from "./CWProposalMultiple.message-composer";
import * as _18 from "./CWProposalSingle.types";
import * as _19 from "./CWProposalSingle.client";
import * as _20 from "./CWProposalSingle.message-composer";
import * as _21 from "./CWTokenSwap.types";
import * as _22 from "./CWTokenSwap.client";
import * as _23 from "./CWTokenSwap.message-composer";
import * as _24 from "./CW4Voting.types";
import * as _25 from "./CW4Voting.client";
import * as _26 from "./CW4Voting.message-composer";
import * as _27 from "./Profiles.types";
import * as _28 from "./Profiles.client";
import * as _29 from "./Profiles.message-composer";
import * as _30 from "./CW721Base.types";
import * as _31 from "./CW721Base.client";
import * as _32 from "./CW721Base.message-composer";
import * as _33 from "./CW721CharacterOnChain.types";
import * as _34 from "./CW721CharacterOnChain.client";
import * as _35 from "./CW721CharacterOnChain.message-composer";
import * as _36 from "./CW721TraitOnChain.types";
import * as _37 from "./CW721TraitOnChain.client";
import * as _38 from "./CW721TraitOnChain.message-composer";
import * as _39 from "./CCATCharacterManager.types";
import * as _40 from "./CCATCharacterManager.client";
import * as _41 from "./CCATCharacterManager.message-composer";
import * as _42 from "./CCATTraitManager.types";
import * as _43 from "./CCATTraitManager.client";
import * as _44 from "./CCATTraitManager.message-composer";
import * as _45 from "./CCATMintables.types";
import * as _46 from "./CCATMintables.client";
import * as _47 from "./CCATMintables.message-composer";
export namespace contracts {
  export const CWAdminFactory = { ..._0,
    ..._1,
    ..._2
  };
  export const CWCore = { ..._3,
    ..._4,
    ..._5
  };
  export const CWNamedGroups = { ..._6,
    ..._7,
    ..._8
  };
  export const CWNamesRegistry = { ..._9,
    ..._10,
    ..._11
  };
  export const CWNativeStakedBalanceVoting = { ..._12,
    ..._13,
    ..._14
  };
  export const CWProposalMultiple = { ..._15,
    ..._16,
    ..._17
  };
  export const CWProposalSingle = { ..._18,
    ..._19,
    ..._20
  };
  export const CWTokenSwap = { ..._21,
    ..._22,
    ..._23
  };
  export const CW4Voting = { ..._24,
    ..._25,
    ..._26
  };
  export const Profiles = { ..._27,
    ..._28,
    ..._29
  };
  export const CW721Base = { ..._30,
    ..._31,
    ..._32
  };
  export const CW721CharacterOnChain = { ..._33,
    ..._34,
    ..._35
  };
  export const CW721TraitOnChain = { ..._36,
    ..._37,
    ..._38
  };
  export const CCATCharacterManager = { ..._39,
    ..._40,
    ..._41
  };
  export const CCATTraitManager = { ..._42,
    ..._43,
    ..._44
  };
  export const CCATMintables = { ..._45,
    ..._46,
    ..._47
  };
}